#!env node

const axios = require('axios')
//var request = require("request");
const app = require('../src/index')
const chai = require('chai')
const chaiHttp = require('chai-http')
const config = {
  port: 3000
};

//CLEAR DATABASE
const client = require('../src/dbClient')
client.flushall();

//PUSH EMPLOYEE
(async function() {
try{
  await Promise.all([{
	id: 'francoisDebout',
	firstname: 'Francois',
	lastname: 'Debout',
	email: "francois.debout@adaltas.com",
	birth: "11/03/1980",
	role: "Director",
	gender: "Man",
	department: "Devops"
},{
	id: 'sergkudinov',
	firstname: 'Sergei',
	lastname: 'Kudinov',
	email: "sergei.kudinov@adaltas.com",
	birth: "11/03/1990",
	role: "Manager",
	gender: "Man",
	department: "Devops"
},{
	id: 'clemencej',
	firstname: 'Clemence',
	lastname: 'Jean-Louis',
	email: "clemence.jldm@adaltas.com",
	birth: "11/03/1990",
	role: "Intern",
	gender: "Woman",
	department: "Devops"
},{
	id: 'louisf',
	firstname: 'Louis',
	lastname: 'Fieux',
	email: "louis.fieux@adaltas.com",
	birth: "11/03/1990",
	role: "Employee",
	gender: "Man",
	department: "Frontend"
},{
	id: 'baptistec',
	firstname: 'Baptiste',
	lastname: 'Catillon',
	email: "batpiste.catillon@adaltas.com",
	birth: "11/03/1990",
	role: "Manager",
	gender: "Man",
	department: "Devops"
},{
	id: 'viviend',
	firstname: 'Vivien',
	lastname: 'Detournay',
	email: "vivien.detournay@adaltas.com",
	birth: "12/02/1990",
	role: "Intern",
	gender: "Man",
	department: "Devops"
},{
	id: 'davidw',
	firstname: 'David',
	lastname: 'Worms',
	email: "david.worms@adaltas.com",
    birth: "10/05/1983",
    role: "Director",
    gender: "Man",
    department: "Frontend"
}].map( async (employee) => {
	 await axios.post(`http://localhost:${config.port}/employee`, (employee))
  }))
  //PUSH DEPARTMENT
  await Promise.all([{
	name: 'Comitte',
},{
	name: 'Devops',
},{
	name: 'Frontend',
}].map( async (department) => {
	 await axios.post(`http://localhost:${config.port}/department`, (department))
  }))
    //PUSH RELATIONS
    await Promise.all([{
	id:'francoisDeboutsergkudinov',
	responsible:'francoisDebout',
	employee:'sergkudinov'
	},{
	id: 'sergkudinovclemencej',
	responsible: 'sergkudinov',
	employee: 'clemencej'
	},{
	id: 'francoisDeboutbaptistec',
	responsible: 'francoisDebout',
	employee: 'baptistec'
	},{
	id: 'sergkudinovviviend',
	responsible: 'sergkudinov',
	employee: 'viviend'
	},{
	id: 'davidwlouisf',
	responsible: 'davidw',
	employee: 'louisf'
}].map( async (relation) => {
	 await axios.post(`http://localhost:${config.port}/relation`, (relation))
  }))
  
  if(!process.env.INIT_BACKEND)
  {
  	console.log("Data pushed, server closed")
  	process.exit()
  }
  console.log("Initialization done")
}catch(err){
console.log(err)
process.exit()
}
})();

